name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Update NPM
        run: npm install -g npm@">=7"
      - name: Use the node_modules cache if available
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ steps.versions.outputs.node_version }}-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npx nx affected --target=build --parallel=3
      - name: Lint Project
        run: npm run lint-project
      - name: Lint Projects
        run: npx nx affected --target=lint --parallel=3
      - name: Nx Integrity Check
        run: npx nx workspace-lint
      - name: Unit Tests
        run: npx nx affected --target=test --parallel=3
      - name: End to End Tests
        run: nx affected --target e2e
